version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: biseutae_postgres
    environment:
      POSTGRES_USER: biseutae
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: biseutae_development
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:

networks:
  my_network:
    driver: bridge
